### PR TITLE
Add in localization

### PR DESCRIPTION
**Pull request by aprilnoren**
I was told that Snagit 2021 is pointing to the fixPathProblem branch.

### CODE REVIEW

**Comment by theeagle** [comment]
Are we going to be able to do a table for this one? I'm just worried having another localizable strings file in a subproject is going to cause issues.

**Comment by aprilnoren** [comment]
I can update this to do a table but that would involve changing a lot more of the code. I wasn't sure if we wanted to do that yet or not.

**Comment by theeagle** [comment]
I was thinking we were just going to add plcrashreporter to the skipped list since all of these strings are low-level error messages, not user-facing strings

**Comment by aprilnoren** [comment]
Deleting this branch and PR since we are just going to ignore those strings for now since they all seem to be internal error messages.

**Pull request closed without merging**
